# Generated by Django 3.1.7 on 2021-03-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210302_1234'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='following_unique',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='author',
            new_name='following',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'following'), name='following_unique'),
        ),
    ]
